### ISSUE TITLE
UCL Nsp13 minimeetings October 2021

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#4]
Local team meeting. Please share what you presented, or some nano notes, by editing this text. _No more than 5 minutes effort_, absolute maximum.

@edwintse 

@TomkUCL 

@jemimahaque 

@lindapatio 

@bhzhx

**Comment by lindapatio** [comment]
[21st October Team Meeting.pdf](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7389534/21st.October.Team.Meeting.pdf)

**Comment by mattodd** [comment]
*** Nsp13 UCL Meeting notes 29/10/21

- [ ] @edwintse Reach out to Joseph at Diamond for nsp13 soaking of our synthesised fragments (ca 2 weeks?). Whats the format, and for shipping?

Toronto (Masoud) doing ATPase assay with 30 uM detection limit, which we think Oxford is developing.
 
- [ ] We need the docking data on our proposed compounds from Kostya. @lindapatio to reach out and get these and post below.

@tmw20653 suggested we just buy the best 300 predictions and send them all for the ATPase assay. And send the same to Joseph if he has capacity. Leapfrog worrying about fragments/crystals. Any synthetic chemistry needs to focus on fragments with new functionality. Alex T would like consensus between FTMap and Glide, i.e. we send Kostya's list if based on Glide and SOME hits from FTMap.

- [ ] @edwintse  - cluster Kostya's hits (he sent the SMILES by email) and post below. Consider what we can make that is similar/useful, or which compound set is representative. Avoid too much overlap/similarity of structures.

- [ ] @edwintse Workflow for finding molecules to buy. Work through an example of how we do this (e.g. using SciFinder, other sites), to ensure we're aligned and have a consistent, exhaustive protocol where we do not miss anything. We compare with UNC's approach.
- [ ] @lindapatio thanks for sharing lab notebook link - please post the link to the overall ELN in the wiki page "sources of data" mimicking [this](https://github.com/OpenSourceMalaria/Series3/wiki/Sources-of-Data).

**Comment by edwintse** [comment]
The file below contains the 100 hits as SMILES from Kostya and a DataWarrior session of the similarity analysis.

[Similarity analysis.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7460294/Similarity.analysis.zip)

**Comment by mattodd** [comment]
@kipUNC - see above for the clustering. Ed's going to have a go with Datawarrior, I think?

**Comment by kipUNC** [comment]
Thank you! If you can select like 10 you like, will be great!

**Comment by lindapatio** [comment]
The file below shows the docking data for the top 200 proposed compounds from Kostya:

[PyMOL (nsp13-site3-denstiyScreen-top200.pse.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7464191/PyMOL.nsp13-site3-denstiyScreen-top200.pse.zip)

**Comment by edwintse** [comment]
Here is what you get from the analysis view of the 100 hits. Clicking on each of the points will colour-code other compounds which are similar (green to red for most to least similar). I'm not sure if there is a way to cluster or rank the compounds in the graph based on the number of similar compounds. @kipUNC is there any other way to do this analysis?

![Screenshot 2021-11-05 at 10 41 26 am](https://user-images.githubusercontent.com/18062981/140498449-9d27fc76-9d8b-4675-be8a-ec8ee5369f05.png)

**Comment by edwintse** [comment]
Current workflow is as follows:

- Perform a substructure search on SciFinder then choose "Get Commercial Sources". View the compounds from particular suppliers (mainly Enamine)

![Screenshot 2021-11-05 at 11 57 12 am](https://user-images.githubusercontent.com/18062981/140507172-2120b324-0e2f-4d72-bdfd-dff2f4712491.png)

- Perform a similarity search on SciFinder and choose filters depending on the number of similar substances. Again view all commercial sources and filter by supplier.
![Screenshot 2021-11-05 at 12 04 08 pm](https://user-images.githubusercontent.com/18062981/140507669-3b81c7c2-c410-4038-9c1d-0230b250d103.png)

- Perform the same substructure and similarity searches on the Enamine website directly
![Screenshot 2021-11-05 at 12 07 33 pm](https://user-images.githubusercontent.com/18062981/140507991-0993ef35-b1c1-48cb-91fe-06c148286004.png)

- Search on ZINC for the compound (also shows MolPort results) and look at Purchasable compounds and any other purchasable compounds based on the scaffold
![Screenshot 2021-11-05 at 12 08 34 pm](https://user-images.githubusercontent.com/18062981/140508058-2fb8cd6b-fbb9-4add-bcd4-8a6e1665bf66.png)

Is there anything else that we should be doing? Is there a more unified and complete search?

**Comment by TomkUCL** [comment]
Nsp13 weekly update 18.11.2021
[nsp13 weekly update 18.11.2021.pptx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7563137/nsp13.weekly.update.18.11.2021.pptx)

**Comment by TomkUCL** [comment]
Nsp13 weekly update 03/12/2021
[nsp13 weekly update 03.12.2021.pptx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7651288/nsp13.weekly.update.03.12.2021.pptx)

**Comment by TomkUCL** [comment]
Update from today's nsp13 meeting:

Molecules in green have been synthesised and shipped to Oxford for soaking. Orange are currently in progress, red is still being route scouted. 
![image](https://user-images.githubusercontent.com/92033163/144641211-d619b28c-185a-4054-8d65-f66c47fe8dc0.png)

Lithiation attempt with nBuLi gives N-alkylated product and starting material (LabArchive link: https://uk-mynotebook.labarchives.com/share/Thomas%2520Knight/MTYuOTAwMDAwMDAwMDAwMDAyfDEwNDQxLzEzL1RyZWVOb2RlLzMyMzg4NTI0ODF8NDIuOQ==)

The pyrrole bromo amide synthesis was scaled up to target 550mg of amide in order to provide sufficient material for trying the following alkylation methods:

![image](https://user-images.githubusercontent.com/92033163/144641387-ba6e36ff-45f3-4a1a-9b42-2fc7ae78f59c.png)

We have previously discussed building a core motif from which we can build a molecule library. One potential route is Pd-catalysed alkylation from pyrrole ethyl ester (£7.50 / 10g), then ester hydrolysis and amide coupling. 
![image](https://user-images.githubusercontent.com/92033163/144642859-75a847dd-789f-4095-b556-a7789bf2d643.png)


We have also been talking with the Brown group abotu applying their ball-milling approach to perfrom direct amidation from the ethyl ester, however this is still in very early stages. Ref: https://doi.org/10.1002/anie.202106412
![image](https://user-images.githubusercontent.com/92033163/144643769-ab02f442-e165-4868-91f2-d29b0def13b5.png)
